// Canonical domain for SEO (used for canonical + OG URL + sitemap/robots)
export const baseUrl = 'https://axiwatt.com';

export const seoConfig = {
  home: {
    title: 'Axiwatt – Energy Autonomy Solutions',
    description: 'Axiwatt delivers bespoke solar architecture and energy autonomy systems for Hyderabad\'s most distinguished private estates. Integrated renewable energy solutions for total independence.',
    keywords: 'axiwatt, axiwatt solar, energy autonomy, luxury solar architecture, solar energy systems, renewable energy, solar pergolas, solar glass facades, sustainable architecture, high-end solar solutions, private estates, Hyderabad',
    ogTitle: 'Axiwatt – Energy Autonomy Solutions',
    ogDescription: 'Axiwatt delivers bespoke solar architecture and energy autonomy systems for Hyderabad\'s most distinguished private estates.',
    ogImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    ogImageWidth: '1200',
    ogImageHeight: '630',
    ogUrl: baseUrl,
    ogType: 'website',
    twitterCard: 'summary_large_image',
    twitterTitle: 'Axiwatt – Energy Autonomy Solutions',
    twitterDescription: 'Transform your private estate with sustainable power autonomy. Axiwatt integrates architecture and renewable energy for intelligent, off-grid living.',
    twitterImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    canonicalUrl: baseUrl
  },
  about: {
    title: 'About Axiwatt – Energy Autonomy Specialists',
    description: 'Discover Axiwatt\'s bespoke energy autonomy systems for premium properties. Axiwatt blends intelligent solar architecture with renewable power for sustainable living.',
    keywords: 'axiwatt about, axiwatt team, solar architecture firm, renewable energy company, luxury estate development, sustainable architecture, energy governance, axiwatt hyderabad',
    ogTitle: 'Luxury Energy Autonomy for Estates | Axiwatt',
    ogDescription: 'Discover bespoke energy autonomy systems for premium properties. Axiwatt blends smart design with renewable power for sustainable living.',
    ogImage: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&q=80&w=1200',
    ogImageWidth: '1200',
    ogImageHeight: '630',
    ogUrl: `${baseUrl}/about`,
    ogType: 'website',
    twitterCard: 'summary_large_image',
    twitterTitle: 'Luxury Energy Autonomy for Estates | Axiwatt',
    twitterDescription: 'Discover bespoke energy autonomy systems for premium properties. Axiwatt blends smart design with renewable power for sustainable living.',
    twitterImage: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&q=80&w=1200',
    canonicalUrl: `${baseUrl}/about`
  },
  products: {
    title: 'Axiwatt Products – Solar Architecture & BIPV Solutions',
    description: 'Axiwatt products include solar pergolas, solar glass facades, and building-integrated photovoltaics. Premium solar architecture solutions for luxury estates.',
    keywords: 'axiwatt products, solar pergolas, solar glass facades, solar railings, walkable solar tiles, building-integrated photovoltaics, BIPV, bioclimatic pergolas, axiwatt solutions',
    ogTitle: 'Axiwatt – Solar & Renewable Energy Architecture',
    ogDescription: 'Leading energy autonomy provider offering solar architecture and intelligent energy systems tailored to distinguished residences.',
    ogImage: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&q=80&w=1200',
    ogImageWidth: '1200',
    ogImageHeight: '630',
    ogUrl: `${baseUrl}/products`,
    ogType: 'website',
    twitterCard: 'summary_large_image',
    twitterTitle: 'Axiwatt – Solar & Renewable Energy Architecture',
    twitterDescription: 'Leading energy autonomy provider offering solar architecture and intelligent energy systems.',
    twitterImage: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&q=80&w=1200',
    canonicalUrl: `${baseUrl}/products`
  },
  technology: {
    title: 'Axiwatt Technology – Smart Energy Management Systems',
    description: 'Axiwatt technology enables complete energy independence with intelligent renewable energy solutions. Features Axiwatt OS, energy storage, EV charging, and smart management.',
    keywords: 'axiwatt technology, axiwatt os, solar technology, energy storage, EV charging, solar modules, battery systems, renewable energy management, intelligent energy systems, axiwatt smart',
    ogTitle: 'Smart Energy-Independent Architecture by Axiwatt',
    ogDescription: 'Achieve complete energy independence with Axiwatt\'s intelligent renewable energy solutions for private estates.',
    ogImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    ogImageWidth: '1200',
    ogImageHeight: '630',
    ogUrl: `${baseUrl}/technology`,
    ogType: 'website',
    twitterCard: 'summary_large_image',
    twitterTitle: 'Smart Energy-Independent Architecture by Axiwatt',
    twitterDescription: 'Achieve complete energy independence with intelligent renewable energy solutions for private estates.',
    twitterImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    canonicalUrl: `${baseUrl}/technology`
  },
  process: {
    title: 'Axiwatt Process – Solar Architecture Design Services',
    description: 'Axiwatt process delivers comprehensive renewable energy system designs for architects and designers. Integrated solar architecture and BIM collaboration tools.',
    keywords: 'axiwatt process, axiwatt services, solar architecture services, architects, designers, solar integration, BIM tools, architectural collaboration, sustainable design, integrated solar',
    ogTitle: 'Renewable Energy Architecture Services | Axiwatt',
    ogDescription: 'Build energy efficient and autonomous living spaces with Axiwatt\'s comprehensive renewable system designs.',
    ogImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    ogImageWidth: '1200',
    ogImageHeight: '630',
    ogUrl: `${baseUrl}/process`,
    ogType: 'website',
    twitterCard: 'summary_large_image',
    twitterTitle: 'Renewable Energy Architecture Services | Axiwatt',
    twitterDescription: 'Build energy efficient and autonomous living spaces with comprehensive renewable system designs.',
    twitterImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    canonicalUrl: `${baseUrl}/process`
  },
  partners: {
    title: 'Axiwatt Partners – Concierge & Energy Management',
    description: 'Axiwatt partners program offers concierge services and lifecycle energy management for your estate. Complete regulatory stewardship and maintenance support.',
    keywords: 'axiwatt partners, axiwatt concierge, concierge services, energy management, lifecycle management, private services, regulatory stewardship, energy consulting, maintenance',
    ogTitle: 'Axiwatt – Intelligent Solar Architecture Experts',
    ogDescription: 'Bespoke solar architecture and sustainability solutions designed for energy-independent estates.',
    ogImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    ogImageWidth: '1200',
    ogImageHeight: '630',
    ogUrl: `${baseUrl}/partners`,
    ogType: 'website',
    twitterCard: 'summary_large_image',
    twitterTitle: 'Axiwatt – Intelligent Solar Architecture Experts',
    twitterDescription: 'Bespoke solar architecture and sustainability solutions designed for energy-independent estates.',
    twitterImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    canonicalUrl: `${baseUrl}/partners`
  },
  privacy: {
    title: 'Privacy Policy | AxiWatt',
    description: 'Learn how AxiWatt protects your data and respects your privacy. Our policy explains collecting, storing, and using personal information.',
    keywords: 'privacy policy, data protection, confidentiality, security, personal data, GDPR, data rights',
    ogTitle: 'Privacy Policy | AxiWatt',
    ogDescription: 'Learn how AxiWatt protects your data and respects your privacy.',
    ogImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    ogImageWidth: '1200',
    ogImageHeight: '630',
    ogUrl: `${baseUrl}/privacy`,
    ogType: 'website',
    twitterCard: 'summary_large_image',
    twitterTitle: 'Privacy Policy | AxiWatt',
    twitterDescription: 'Learn how AxiWatt protects your data and respects your privacy.',
    twitterImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    canonicalUrl: `${baseUrl}/privacy`
  },
  terms: {
    title: 'Terms & Conditions | AxiWatt',
    description: 'Read the terms and conditions governing the use of AxiWatt\'s website and services — transparency and user trust guaranteed.',
    keywords: 'terms of service, terms and conditions, legal terms, user agreement, service terms',
    ogTitle: 'Terms & Conditions | AxiWatt',
    ogDescription: 'Read the terms and conditions governing the use of AxiWatt\'s website and services.',
    ogImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    ogImageWidth: '1200',
    ogImageHeight: '630',
    ogUrl: `${baseUrl}/terms`,
    ogType: 'website',
    twitterCard: 'summary_large_image',
    twitterTitle: 'Terms & Conditions | AxiWatt',
    twitterDescription: 'Read the terms and conditions governing the use of AxiWatt\'s website and services.',
    twitterImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    canonicalUrl: `${baseUrl}/terms`
  }
};
